export const AGENT_AUDIT_ACTIONS = {
  AGENT_REGISTERED: 'AGENT_REGISTERED',
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_NEED_MORE_INFO: 'KYC_NEED_MORE_INFO',
  AGENT_CREDITED: 'AGENT_CREDITED',
  AGENT_SUSPENDED: 'AGENT_SUSPENDED',
  AGENT_API_KEY_GENERATED: 'AGENT_API_KEY_GENERATED',
} as const;

export const AGENT_API_KEY_PREFIX = 'ak_';
export const AGENT_SECRET_KEY_PREFIX = 'sk_';
