export const BCRYPT_ROUNDS = 12;

export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  IMPERSONATION_START: 'IMPERSONATION_START',
  IMPERSONATION_STOP: 'IMPERSONATION_STOP',
  AGENT_MEMBER_ROLE_CHANGE: 'AGENT_MEMBER_ROLE_CHANGE',
  AGENT_MEMBER_INVITE: 'AGENT_MEMBER_INVITE',
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
