export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  AGENT_SUSPENDED: 'AGENT_SUSPENDED',
  AGENT_INACTIVE: 'AGENT_INACTIVE',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_SKU: 'INVALID_SKU',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  MISSING_REQUEST_ID: 'MISSING_REQUEST_ID',
  ORDER_AMOUNT_LIMIT: 'ORDER_AMOUNT_LIMIT',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
