export const FINANCE_PERMISSIONS = {
  VIEW: 'finance.view',
  MANAGE: 'finance.manage',
} as const;

export const FINANCE_AUDIT_ACTIONS = {
  RECONCILE_CREATED: 'RECONCILE_CREATED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
} as const;

export const FINANCE_PAGINATION_DEFAULT = 50;
export const FINANCE_PAGINATION_MAX = 100;

export const FINANCE_MAX_DATE_RANGE_DAYS = 366;
export const FINANCE_MAX_RECONCILE_LINES = 5000;
export const FINANCE_MAX_LEDGER_ROWS = 10000;
export const FINANCE_MAX_INTERNAL_QUERY_ROWS = 10000;

/** User-facing alias — schema uses MISSING_LOCAL */
export const RECONCILE_STATUS_LABEL = {
  MATCHED: 'MATCHED',
  MISMATCH: 'MISMATCH',
  MISSING_GATEWAY: 'MISSING_GATEWAY',
  MISSING_INTERNAL: 'MISSING_INTERNAL',
} as const;
