export const NOTIFICATION_CHANNEL = {
  EMAIL: 'EMAIL',
  SYSTEM: 'SYSTEM',
  WEBHOOK: 'WEBHOOK',
  TELEGRAM: 'TELEGRAM',
} as const;

export type NotificationChannel =
  (typeof NOTIFICATION_CHANNEL)[keyof typeof NOTIFICATION_CHANNEL];

export const EMAIL_TEMPLATE = {
  USER_REGISTER: 'USER_REGISTER',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  CARD_DELIVERY: 'CARD_DELIVERY',
  CARD_DELIVERED: 'CARD_DELIVERED',
  TOPUP_SUCCESS: 'TOPUP_SUCCESS',
  DATA_SUCCESS: 'DATA_SUCCESS',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  AGENT_APPROVED: 'AGENT_APPROVED',
  AGENT_KYC_REJECTED: 'AGENT_KYC_REJECTED',
  AGENT_KYC_NEED_MORE_INFO: 'AGENT_KYC_NEED_MORE_INFO',
  AGENT_LOW_BALANCE: 'AGENT_LOW_BALANCE',
  AGENT_API_DISABLED: 'AGENT_API_DISABLED',
  PROVIDER_LOW_BALANCE: 'PROVIDER_LOW_BALANCE',
  CONTACT_FORM: 'CONTACT_FORM',
} as const;

export type EmailTemplateType =
  (typeof EMAIL_TEMPLATE)[keyof typeof EMAIL_TEMPLATE];

export const SYSTEM_NOTIFICATION_TYPE = {
  PROVIDER_LOW_BALANCE: 'PROVIDER_LOW_BALANCE',
  LOW_BALANCE: 'LOW_BALANCE',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  MANUAL_REVIEW_ORDER: 'MANUAL_REVIEW_ORDER',
  ADMIN_RETRY_REQUIRED: 'ADMIN_RETRY_REQUIRED',
  MANUAL_PAYMENT_REVIEW: 'MANUAL_PAYMENT_REVIEW',
  AGENT_API_DISABLED: 'AGENT_API_DISABLED',
  NEW_CONTACT: 'NEW_CONTACT',
  NEW_SUPPORT_TICKET: 'NEW_SUPPORT_TICKET',
} as const;

export const CUSTOMER_NOTIFICATION_TYPE = {
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  CARD_DELIVERED: 'CARD_DELIVERED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_NEED_SUPPORT: 'ORDER_NEED_SUPPORT',
  TOPUP_DELIVERED: 'TOPUP_DELIVERED',
  SUPPORT_REPLY: 'SUPPORT_REPLY',
  AGENT_DEPOSIT_CREDITED: 'AGENT_DEPOSIT_CREDITED',
  AGENT_DEPOSIT_FAILED: 'AGENT_DEPOSIT_FAILED',
  AGENT_DEPOSIT_EXPIRED: 'AGENT_DEPOSIT_EXPIRED',
} as const;

export const NOTIFICATION_JOB = {
  SEND: 'notification.send',
} as const;

export const NOTIFICATION_MAX_ATTEMPTS = 3;
export const NOTIFICATION_RETRY_DELAY_MS = 5000;

export const AGENT_LOW_BALANCE_THRESHOLD = 100_000;
